import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Din Mægler',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <body className={inter.className}>
        <header>
          <h1>{metadata.title}</h1>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
